### ISSUE TITLE
Nejde nakonfigurovat

### ISSUE THREAD

**Issue by masch7319** [slesinger/HomeAssistant-PREdistribuce#2]
Zdravím,
nedaří se mi senzor rozjet, postupoval jsem podle návodu, ale v logu HA se při startu zobrazí chyba:

2020-09-23 12:46:49 ERROR (MainThread) [homeassistant.components.binary_sensor] Error while setting up predistribuce platform for binary_sensor
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 193, in _async_setup_platform
await asyncio.shield(task)
File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/predistribuce/binary_sensor.py", line 45, in setup_platform
for pre in conf_periods:
TypeError: 'NoneType' object is not iterable

V config mám jen:
binary_sensor:

  - platform: predistribuce
    "#"name: nocni proud
    receiver_command_id: 561
(pokud odkomentuji name, neprojde Kontrola konfigurace: Invalid config for [binary_sensor.predistribuce]: [name] is an invalid option for [binary_sensor.predistribuce]. Check: binary_sensor.predistribuce->name. (See ?, line ?). )

Kde mohu mít chybu? Díky moc!

**Comment by slesinger** [comment]
Diky za reportovani chyby, kterou jsem snad ted jiz opravil. Problem byl, ze program se spolehal na to, ze v konfiguraci budou i ```periods```. Zkuste svou konfiguraci po aktualizaci modulu. Diky.
